version: "3"
services:
    mysql:
        build: ./mysql
        image: localhost:5000/mysql:5.7
    openjdk:
        build: ./openjdk
        image: localhost:5000/openjdk:14
    elasticsearch:
        build: ./elasticsearch
        image: localhost:5000/elasticsearch:6.4.3
        depends_on:
            - openjdk
